name: Auto Contributions

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add multiple commits
        run: | 
          for i in {1..100}
          do
            echo "$(date): Commit $i" > update_$i.txt
            git add update_$i.txt
            git commit -m "Auto update $(date): Commit $i"
          done
          git push
