name: Auto Contributions

on:
  schedule:
    # Run at 11:14am IST (5:44am UTC) every day
    - cron: '44 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git user
        run: | 
          git config --global user.name "NihalSandarwale"
          git config --global user.email "nihalsandarwale@gmai.com"

      - name: Add multiple commits
        run: | 
          for i in {1..100}
          do
            echo "$(date): Commit $i" > update_$i.txt
            git add update_$i.txt
            git commit -m "Auto update $(date): Commit $i"
          done
          git push
