name: Auto Contributions

on:
  schedule:
    # Run at 11:16am IST (5:46am UTC) every day
    - cron: '46 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Configure git user
        run: | 
          git config --global user.name "NihalSandarwale"
          git config --global user.email "nihalsandarwale@gmail.com"

      - name: Add multiple commits
        run: | 
          # Generate random number between 1500 and 3000
          num_commits=$((1500 + RANDOM % 2001))
          echo "Number of commits to be made: $num_commits"
          
          for ((i=1; i<=num_commits; i++))
          do
            echo "$(date): Commit $i" > update_$i.txt
            git add update_$i.txt
            git commit -m "Auto update $(date): Commit $i"
          done

      - name: Push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: | 
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
